# Generated by Django 3.0.4 on 2020-03-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('no_confirmed', models.IntegerField(blank=True, null=True, verbose_name='Nr de pacienți confirmați cu coronavirus')),
                ('no_special_quarantined', models.IntegerField(blank=True, null=True, verbose_name='Nr de pacienți în carantina specializata')),
                ('no_self_quarantined', models.IntegerField(blank=True, null=True, verbose_name='Nr de persoane în self quarantine')),
                ('no_recovered', models.IntegerField(blank=True, null=True, verbose_name='Nr de persoane vindecate')),
                ('global_no_confirmed', models.IntegerField(blank=True, null=True, verbose_name='Numărul total de cazuri confirmate la nivel global')),
                ('global_no_deaths', models.IntegerField(blank=True, null=True, verbose_name='Nr total de decese la nivel global')),
                ('global_no_recovered', models.IntegerField(blank=True, null=True, verbose_name='Nr total de persoane vindecate la nivel global')),
            ],
        ),
    ]
